### ISSUE TITLE
Traceback (most recent call last):   File "asu.py", line 5, in <module>   File "<string>", line 5, in <module>   File "<string>", line 5, in <module>   File "<string>", line 29, in <module> ModuleNotFoundError: No module named 'bs4'

### ISSUE THREAD

**Issue by Darksourov** [SoraDev-ID/SoraClone#1]
Traceback (most recent call last):
  File "asu.py", line 5, in <module>
  File "<string>", line 5, in <module>
  File "<string>", line 5, in <module>
  File "<string>", line 29, in <module>
ModuleNotFoundError: No module named 'bs4'

**Comment by SoraDev-ID** [comment]
pip install bs4
